apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Probar con: kubectl port-forward svc/uptime-kuma 3001:3001
namespace: default

patches:
  - path: patch-virtual-node.yaml
  - path: patch-slow-start.yaml
