apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  annotations:
    checkov.io/skip1: "CKV_K8S_21=mismo motivo que deployment.yaml - namespace default a proposito"
spec:
  selector:
    app: uptime-kuma
  ports:
    - name: http
      port: 3001
      targetPort: http
